# This is a basic workflow to help you get started with Actions

name: CI on ln-specific branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "ln-specific" branch
  push:
    branches: [ "ln-specific" ]
  pull_request:
    branches: [ "ln-specific" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install Ninja
      - name: Install Ninja on Linux
        run: sudo apt-get install ninja-build

      - name: Install Python Packages
        run: |
          sudo pip3 install lit numpy
          sudo pip3 install pybind11

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja llvm \
            -DLLVM_ENABLE_PROJECTS=mlir \
            -DLLVM_TARGETS_TO_BUILD="host" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_RTTI=ON \
            -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
            -DLLVM_ENABLE_LIBEDIT=OFF ;

      - name: Build
        run: cd build && ninja
